### PR TITLE
[FixTempt] Try to fix: WebUI download information mismatch the log

### PR DESCRIPTION
**Pull request by rong-xiaoli**
2024/04/11 UTC+0800 02:53
A tempt of fixing the problem which WebUI info is not corresponded to the log.

### CODE REVIEW

**Comment by rong-xiaoli** [comment]
From issue #738

**Comment by rong-xiaoli** [comment]
累了，睡觉！

**Comment by EstrellaXD** [comment]
cc @Rewrite0

**Comment by Rewrite0** [comment]
> cc @Rewrite0

没有前端部分 -v-

**Comment by rong-xiaoli** [comment]
😭不会前端
等我学

**Pull request closed without merging**
